version: "3"
services:
  base:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - .:/app
  start:
    extends:
      service: base
    command: npm run dev
    env_file:
      - .env
  install:
    extends:
      service: base
    command: npm i
