version: "3"
services:
  server:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - .:/app
    command: npm run dev
    env_file:
      - .env
    ports:
      - "8080:8080"
