version: "3"
services:
  server:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - data:/app/data/
      - ./:/app
volumes:
  data:
